import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fun Fiction Storage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <header>
          <nav>
            <ul>
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="about">About</a>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer>@ all rights reserved.</footer>
      </body>
    </html>
  );
}
